### ISSUE TITLE
In Right To Left (RTL) language the beginning of a message is truncated

### ISSUE THREAD

**Issue by sbraitbart** [kontalk/androidclient#653]
When receiving/sending a message in RTL (Hebrew for example) which is longer than the screen width (or perhaps the message balloon width). a few letters at the beginning of each line are truncated (that is on the right side of the screen). This sometimes makes the message non readable.

**Comment by sbraitbart** [comment]
Android version 5.1.1 on Sony Xperia Z3 Compact (D5803)

**Comment by daniele-athome** [comment]
Thanks for reporting! We'll test it and find a fix as soon as we can.

**Comment by daniele-athome** [comment]
I can't really reproduce it, can you send a screenshot and some example text to paste into the app to reproduce the issue please?

**Comment by sbraitbart** [comment]
Hi.
I attach a screen shot. the truncations are marked. 
Any text in hebrew will do as long as it is long enough. you can try and insert the below sample text:

טקסט בדיקה לחיתוך מילים. צריך שהמשפט יהיה ארוך מספיק כדי שיהיו מספיק שורות בבלון הטקסט

same issue in my wife's phone which is SAMSUNG A5
  
![screenshot_rtlmarked](https://cloud.githubusercontent.com/assets/17427276/13378266/dd7191b0-de08-11e5-9f00-bfbd7773a930.png)

**Comment by daniele-athome** [comment]
Oh you are using the classic theme, I tested with Hangout theme :-)
I'll work on it as soon as I can.

**Comment by sbraitbart** [comment]
Actually it happens in all themes. I tried all of them including Hangout.

**Comment by daniele-athome** [comment]
I see. I've tried with the emulator on Android 4.4 and 5.0, I'll try again with a 5.1 emulator. Honestly I did a quick test only so far because of lack of time, I'll be more thorough next time. Thanks for your patience!

**Comment by daniele-athome** [comment]
@sbraitbart did you download Kontalk from Google Play? If so, I'm uploading a new alpha version that should fix your issue, could you try that please? Join alpha testing here https://play.google.com/apps/testing/org.kontalk
New version should be deployed in a few minutes + a few hours for Google Play propagation.

**Comment by sbraitbart** [comment]
I dont use google play only F-Droid. is it possible to get it another way?

**Comment by daniele-athome** [comment]
I could send a prebuilt apk to you, with a different package name and application icon (to be installed separately from the current installation). What do you think?

**Comment by sbraitbart** [comment]
Thanks! 
If you send me a prebuilt apk I will try to install it. 
Can both the pre-built app and the original app work in parallel or will
I need to uninstall the original?
Will there be a key import issue?
I would prefer to have the original working so it will be easier to
update in the future.

**Comment by daniele-athome** [comment]
Yes, you can install both. But you'll have to reuse the same key (export in the old one > import in the new one), and you can't keep both of them online at the same time: one of them must be offline (menu > go offline) otherwise they will go into conflict and keep disconnecting each other.

I will send you the apk later tonight.

**Comment by sbraitbart** [comment]
Great thanks

**Comment by daniele-athome** [comment]
Sorry for the late reply. Here is your apk: http://astra.casaricci.it/public/Kontalk-3.1.4-test-20160401.apk

**Comment by sbraitbart** [comment]
Thanks!
But the bug is still there. Long messages still get trimmed.
Let me know if I can help in any way 

Shlomi

On April 2, 2016 4:04:27 PM GMT+03:00, Daniele Ricci <notifications@github.com> wrote:
>Sorry for the late reply. Here is your apk:
>http://astra.casaricci.it/public/Kontalk-3.1.4-test-20160401.apk
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/653#issuecomment-204713779

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daniele-athome** [comment]
Could you try this please?
http://astra.casaricci.it/public/Kontalk-3.1.4-test-20160403.apk

I wish I had a Samsung to do some tests myself :-(

**Comment by sbraitbart** [comment]
Now it seems to work both on my sony Z3 compact and my wifes Samsung
A5 :-D
Thanks!!!

Shlomi

**Comment by daniele-athome** [comment]
Fixed in f9895141dee702ae7d8e535460a60b4f829bf2c0.

**Comment by sbraitbart** [comment]
Hi,
After using the app for a while I am sad to say that the bug is still there.
It is not consistent. some time the messages are fine and other times I get the clipping on the right.
I couldn't find consistent behavior. some messages are clipped and others are not.
Is there a log or something I can do to help fix it?
thanks.

Shlomi

**Comment by daniele-athome** [comment]
Sorry to hear that. I'll reopen it and do some tests tonight before the 3.1.5 hotfix release, but I can't promise anything: Samsung heavily modifies Android so it could be very well a system bug.

Anyway: I can see it probably happens only for multiline messages, single line messages seem to be not affected by the issue. I might have a couple of things for you to try. I'll be back later with a test apk for you.

**Comment by sbraitbart** [comment]
Thanks.
I am using Sony z3 compact, and my wife Samsung, so its not only Samsung. The sms app "smssecure" never had that problem. So i dont think this is system issue.

Shlomi

On April 7, 2016 3:42:04 PM GMT+03:00, Daniele Ricci <notifications@github.com> wrote:
>Sorry to hear that. I'll reopen it and do some tests tonight before the
>3.1.5 hotfix release, but I can't promise anything: Samsung heavily
>modifies Android so it could be very well a system bug.
>
>Anyway: I can see it probably happens only for multiline messages,
>single line messages seem to be not affected by the issue. I might have
>a couple of things for you to try. I'll be back later with a test apk
>for you.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/653#issuecomment-206868933

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sbraitbart** [comment]
After upgrading to 3.1.5 all works well
