### ISSUE TITLE
Can't send an image to a group chat

### ISSUE THREAD

**Issue by StefanBrand** [kontalk/androidclient#871]
### Expected behavior
The image is sent as usual. 

### Actual behavior
When I click share the image dialogue opens, but when I click the image a new private chat with the name "image:12345" opens. (5-digit number changes with the image).

### Steps to reproduce
1. Start group chat with 3 people, including you.
2. Try to share an image.
3. A PM with the header "image:xxxxx" opens. No image is sent.

### Environment

Kontalk version: Kontalk 4.0.0 beta1-basic

Android version: Android KitKat 4.4.2

Device model: Fairphone 1

### Other

We can receive images from the second person in the group chat, but the third person experiences the same issue like me. We couldn't yet find out the differences between us (it's not the device, not the Android version, not basic/google-play, etc.)

**Comment by daniele-athome** [comment]
Thanks for reporting! I was able to reproduce it. I still can't tell why the second person isn't affected by this issue, but I will tell you soon enough :-)

**Comment by daniele-athome** [comment]
Is the second person using alpha8 by any chance?

**Comment by StefanBrand** [comment]
No, we all have the beta1 installed.

**Comment by StefanBrand** [comment]
Not solved by the [latest beta](https://forum.kontalk.org/t/preview-kontalk-for-android-4-0-0-beta1-preview/75?u=stefan). I get a notification saying "Fehler beim Hochladen" (_Error during upload_).

**Comment by StefanBrand** [comment]
Wow, I get that notification every time I turn on my network. Pretty annoying!

**Comment by webratte** [comment]
@stefanbrand
If you delete the Image wich can not send, the notification should not appeare anymore.

**Comment by daniele-athome** [comment]
Thanks @StefanBrand, just fixed in 5a65bae2ba3ccd7d7de95795b42eeb02b55a2348. I'm uploading beta1 (212) right now. I'll update [the post on the forum](https://forum.kontalk.org/t/preview-kontalk-for-android-4-0-0-beta1-preview/75).

**Comment by StefanBrand** [comment]
@webratte: Haha, yes of course! Thank you! 😁
@danieleathome

I'll try the beta as soon as possible.
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 2. Dezember 2016 13:56:22 MEZ, schrieb webratte <notifications@github.com>:
>@stefanbrand
>If you delete the Image wich can not send, the notification should not
>appeare anymore.

**Comment by StefanBrand** [comment]
Still doesn't work (at least not on 3G). I don't get a notification anymore, but the little clock symbol doesn't turn into a check mark.

Should I make a log?

**Comment by daniele-athome** [comment]
Yes please.

**Comment by StefanBrand** [comment]
Ok sorry, I fell for that trap! I tried in the old chat, which didn't work. It works in newly created chats! :)
